stages:
  - build
  - deploy

build:
  stage: build
  image: node:14
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: google/cloud-sdk
  before_script:
    - echo $GCLOUD_SERVICE_KEY > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  script:
    - gcloud app deploy --project your-project-id --version $CI_PIPELINE_ID --no-promote
  only:
    - Frontend
